name = "biridiet"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat", "transform_dot_vercel_output"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "birivibe-db"
database_id = "f0eb042b-ec99-4149-a449-27812b56792c"
