name = "birivibe"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[vars]
NODE_ENV = "production"

[[d1_databases]]
binding = "BIRILIFE"
database_name = "BIRILIFE"
database_id = "f0eb042b-ec99-4149-a449-27812b56792c"
