name = "birivibe"
compatibility_date = "2024-01-31"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "birivibe-db"
database_id = "f0e0-seu-id-aqui" # VocÃª cria isso no painel do Cloudflare em 10 segundos
